### ISSUE TITLE
Client: Reply to private message?

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#114]
Hello again, good to see Mobius getting updates.  Hope you are doing well :)

I've just installed the recently compiled client and it works well but noticed there is no way to reply to any private messages currently (unless I'm missing something).  Appreciate ititss not a full blown client but this would be useful.

**Comment by aptonline** [comment]
Wow I was not aware of that app, thanks for the heads up. Looks like they are promoting Mobius which is a good thing.

Something cool about using Hotline via the terminal though so hopefully you’ll get your mojo back at some point 😉

**Comment by jhalter** [comment]
I've split off the client to a separate repo with a Project Status table in the README that acknowledges this as a currently unimplemented feature.  I'm going to close this issue.

https://github.com/jhalter/mobius-hotline-client
