### ISSUE TITLE
GPTBot

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#115]
Do you have any plans to release the GPTbot for use with Mobius?

**Comment by jhalter** [comment]
Yeah, I need to remove some hardcoded configuration and make it more cost-efficient to run first.  If you're interested in running it, I can package it in a Docker image for you.  You'd need to bring your own OpenAPI token though.

**Comment by aptonline** [comment]
Yeah I’d be interested in giving it a go 👍

**Comment by aptonline** [comment]
Any progress? happy to test.

**Comment by jhalter** [comment]
I have some time off next week and will try to release this.

**Comment by jhalter** [comment]
I've released the bot as a separate project [here](https://github.com/jhalter/mobius-gpt-bot).  You'll find setup instructions along with precompiled binaries and a Docker image.

If you run it, let me know how it goes!
