### ISSUE TITLE
Option to bind another IP

### ISSUE THREAD

**Issue by Tazintosh** [jhalter/mobius#116]
Hi,

I'm running Mobius —huge thanks for this— on a Mac mini M1 used as server for many other things.
The server network is set to two VLANs, one is a "Family", the other a "Services".
So for instance, I'm running httpd, node-red, mqtt, etc. on the Services Network using an option in the config file of those processes.
Would it be possible to implement this into the config.yam file? `BindIP: 10.0.0.1`
Binding port could be a nice addition too.

Thanks in advance for the consideration.

**Comment by jhalter** [comment]
Hi, I've just released `v0.11.0` which adds a `--interface` flag that will let you specify the interface to listen on (e.g. `--interface=10.0.0.1`).  If you want change the port you can use the existing `--bind` flag (e.g. `--bind=5600`).  This would make the API server listen on 5600 and the file transfer server on 5601.

Hope this helps!

**Comment by Tazintosh** [comment]
Awesome!
Can those flags be set inside the config.yam too?
Is there an up to date config.yam example BTW?

**Comment by jhalter** [comment]
At least for now the interface and port can only be set as command line flags, as this is the simplest path forward that isn't a breaking change from previous version.  I may be open to revisiting this in the future, but I want to tackle some other tasks first.

Here's the source of the default config.yaml:
https://github.com/jhalter/mobius/blob/master/cmd/mobius-hotline-server/mobius/config/config.yaml

**Comment by jhalter** [comment]
Hey, thanks and glad you're enjoying the software!

Regarding banners: the only clients I know of with banner support are the classic 1.8 client and mierau's [new macOS client](https://github.com/mierau/hotline)

**Comment by Tazintosh** [comment]
I'm running Hotline-Client-1.9.2 on Mac OS 9 and the banner does start loading (at least on the progress bar), but never seems to finish.
I never saw the banner on mierau's client, don't even know where it should display.

**Comment by jhalter** [comment]
The 1.9 client banner question has come up a few times, so I wrote up my understanding of what's happening based on notes from a couple year back:

https://github.com/jhalter/mobius/wiki/Hotline-1.9.2-client-banners

In mierau's client, you'll see the banner at the top of the public chat window pane.
