### ISSUE TITLE
FileRoot NOT as subdirectory?

### ISSUE THREAD

**Issue by Tazintosh** [jhalter/mobius#118]
Hi,

I've configured my FileRoot to "/Volumes/SomeDriveName".
Looks like it's not working. Is it implemented?

Thanks for the support and Happy Easter!

**Comment by jhalter** [comment]
Hi, I thought this was working.  What OS are you running on?

**Comment by Tazintosh** [comment]
My M1 Server is running Ventura 13.3.1 (22E261)

**Comment by jhalter** [comment]
@Tazintosh Thanks for point this out.  Should be fixed in v0.11.1 now.

**Comment by Tazintosh** [comment]
Big thanks.
