### ISSUE TITLE
Server Follow Symlinks?

### ISSUE THREAD

**Issue by armadillu** [jhalter/mobius#121]
Hi, first of all, thanks for making this happen! Second, the following is more a request than an issue, so feel free to ignore.

I am wondering if the server is supposed to follow symlinks under the Files section; they are currently ignored (not listed at all) when I try it on my server (running Raspbian).

I see the related code is [here](https://github.com/jhalter/mobius/blob/5b8da5035083a849d6116672c8701cc9c184a830/hotline/files.go#L53) but I don't know enough Go to figure out what the intention is here.

I can see how this could be a security issue (as it was back then with people uploading aliases to access parts of the server), but maybe it could be an optional config? It is rather handy if you are hosting the same files across several services... 

Thanks!

**Comment by jhalter** [comment]
Hi, thanks for reaching out.  

I think I deferred on this for lack of specific personal need and desire to avoid cross-platform incompatibilities, but following symlinks seems like a reasonable thing to support.  I'll investigate.

**Comment by jhalter** [comment]
On closer inspection, following symlinks used to work but I broke it.  I've just released v0.12.1 with a fix.

**Comment by armadillu** [comment]
I can confirm symlinks work on my setup (on Raspbian) with this release (v0.12.1); thank you!
