### ISSUE TITLE
I would like a little help...

### ISSUE THREAD

**Issue by andreiixe** [jhalter/mobius#152]
I have set everything up on a Debian Linux system, and it's all functional, but when I try to log in, the admin user doesn't work in any way. I've tried everything—it simply says the password is incorrect, even though I copied and pasted the exact password from the YAML file, word for word... but it still doesn't work. Could you explain step by step?

I ran ./mobius-hotline-server -init -config config, etc., but the admin user doesn't work at all (note: I set it up without Docker). Thank you if you can help.

**Comment by jhalter** [comment]
Hi @andreiixe, the YAML file contains a hash of the password, not the actual password.  In this case the initial password for the admin user is also "admin".  

Hope that helps -- if not, let me know.

**Comment by andreiixe** [comment]
@jhalter thanks 🤍

**Comment by andreiixe** [comment]
Problem solved, thanks for your help 😶‍🌫️
