### ISSUE TITLE
Implement resume of file transfers

### ISSUE THREAD

**Issue by jhalter** [jhalter/mobius#16]
For uploads, the behavior of the official Hotline Server seems to be something like:

1. Client starts transfer
2. Server starts writing bytes to a file with type/creator code HTft/HTLC
3. After transfer finishes, type/creator codes are swapped with the actual file creator codes

In absence of type/creator codes on filesystems with resource forks, I think I'll write to a temp file with an `.incomplete` suffix tacked on, then rename after transfer finishes.  Files with `.incomplete` will return HTft/HTLC type/creator to Hotline clients so that they will see the file as a resumable partial transfer.

Seems to be working in first quick and dirty attempt.

**Comment by pfuentes69** [comment]
Hello.
I tried the new build...

I interrupted the network connection while doing a transfer, and when I went back to the file list, the client showed it as interrupted.
![IMG_2449](https://user-images.githubusercontent.com/34808198/172003505-efcae09a-974f-4f61-809d-19ca06ca7b3b.jpg)

Then, trying to upload it again the client proposed to resume it.
![IMG_2450](https://user-images.githubusercontent.com/34808198/172003525-18284071-f2c4-4291-91d7-8b58d06e76cf.jpg)

So, I'd say it works nicely.

Txs!
