### ISSUE TITLE
Server crash on upload

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#18]
attempting to upload file gives me the following error and the server crashes.

```
panic: runtime error: slice bounds out of range [:8876] with capacity 1024

goroutine 9 [running]:
github.com/jhalter/mobius/hotline.ReadFlattenedFileObject({_, _, _})
	/private/tmp/mobius-hotline-server-20220603-3101-1vmi7dg/mobius-0.0.12/hotline/flattened_file_object.go:120 +0x630
github.com/jhalter/mobius/hotline.(*Server).TransferFile(0xc000172000, {0x13048b8?, 0xc000010008})
	/private/tmp/mobius-hotline-server-20220603-3101-1vmi7dg/mobius-0.0.12/hotline/server.go:681 +0x1ce
github.com/jhalter/mobius/hotline.(*Server).ServeFileTransfers.func1()
	/private/tmp/mobius-hotline-server-20220603-3101-1vmi7dg/mobius-0.0.12/hotline/server.go:96 +0x2e
created by github.com/jhalter/mobius/hotline.(*Server).ServeFileTransfers
	/private/tmp/mobius-hotline-server-20220603-3101-1vmi7dg/mobius-0.0.12/hotline/server.go:95 +0x11e

```

**Comment by jhalter** [comment]
Hi, looks like you're using an older release with some known issues.

Can you try the latest from here?  https://github.com/jhalter/mobius/releases/tag/v0.2.3

I'll be releasing a newer v0.3.0 version this weekend that supports resume for file transfers, so keep an eye out for that as well.

**Comment by jhalter** [comment]
I realized I haven't updated the brew formula in a bit, so if you're using brew try upgrading to the latest version:

`brew update && brew upgrade jhalter/mobius-hotline-server/mobius-hotline-server`

**Comment by jhalter** [comment]
Closing as fixed, but let me know if you run into problems with the latest version from brew or Docker.
