### ISSUE TITLE
Docker Image size

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#20]
Just looking at transferring the image I built this morning over to my server and noticed that the image size was a lot larger than expected 1.07GB to be exact.  Why would this be so large?
![Screenshot 2022-06-04 at 19 48 14](https://user-images.githubusercontent.com/190136/172021557-fea9f53b-642f-4736-b1d9-56eeb7fea4e0.png)

**Comment by jhalter** [comment]
Ouch, yeah that's huge.  It's because I'm using the golang image as the base.  

I just updated the Docker file to use a multi-stage build and the new image size is 6.71MB. 🎉

**Comment by jhalter** [comment]
Closing as fixed.
