### ISSUE TITLE
Investigate multiple compatibility issues with the Nostalgia client

### ISSUE THREAD

**Issue by jhalter** [jhalter/mobius#26]
Lots of broken behavior observed with the Nostalgia client.  

TODO: see if this is due to bad behavior in Nostalgia or Mobius; if latter, fix

**Comment by aptonline** [comment]
Some of the comments on MacintoshGardens page lead me to think it’s Nostalgia that’s at fault.

https://macintoshgarden.org/apps/nostalgia-0

I also read somewhere that the developer passed away.

**Comment by jhalter** [comment]
Sorry to hear that the developer passed, if so. 😢 

If Nostalgia works with the official server, I consider whatever it's doing as legit and would like to maintain compatibility, especially since Nostalgia is the only OSX client (I think?).  

It seems like the difference in behavior is that the official Hotline client will always send zeros for empty fields, but Nostalgia omits the field instead.  For example, if a file has no comment, official HL sends `00 00` for the comment length, while Nostalgia sends nothing.

Should be fixable.

**Comment by jhalter** [comment]
Everything I can think of testing seems to be working fine now.  Closing.
