### ISSUE TITLE
Mobius Logo

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#32]
You can't have a project without a project logo 🤣.

But seriously I was putting together a banner for RetroMac (in preparation for it being supported in Mobius😉) and while I was doing so I thought I'd promote Mobius at the same time and what better way to do so than to add a logo to the banner.

![Mobius Logo](https://user-images.githubusercontent.com/190136/173185950-97082929-81d8-42d4-9035-fff3f4fec919.png)

**Comment by jhalter** [comment]
Wow, that's great!  Thanks for putting that together!  🏆  

I'll see about adding banner support.
