### ISSUE TITLE
Path for config flag should not be required to have a trailing slash

### ISSUE THREAD

**Issue by benabernathy** [jhalter/mobius#38]
When building and running the latest version of mobius server (Windows 10 WSL), the path given to --config must end with a '/'. 

```
> ./mobius-hotline-server --config ./config
2022-06-19T16:30:03.800-0600    fatal   open ./configAgreement.txt: no such file or directory
> ./mobius-hotline-server --config ./config/
2022-06-19T16:30:06.609-0600    info    Hotline server started  {"version": "0.5.6", "API port": ":5500", "Transfer port": ":5501"}
```

It's a minor usability issue, but the path should not have to include that trailing slash.

**Comment by jhalter** [comment]
Thanks for the feedback, will fix. 👍

**Comment by benabernathy** [comment]
I can take a look if you’d like.

**Comment by jhalter** [comment]
Sure, any help you can offer is appreciated 👍

**Comment by jhalter** [comment]
Yeah, I agree.  I'm using `path/filepath` in some places, but not consistently.  There's a bunch of work to do there.

I'll be working on a cleanup pass to add more testing and fix stuff like this over the next week.
