### ISSUE TITLE
Exclude @eaDir directory from Hotline file navigator

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#44]
As I'm hosting Mobius on a Synology via Docker  it creates an extended attribute directories (@eaDir) when I interact with the file structure on the Synology.  Is there any way for Mobius to ignore directories of this name and not display them in the file navigator?

![image](https://user-images.githubusercontent.com/190136/175789325-458ba37e-ad49-4aff-85fb-3313d6294d2f.png)

**Comment by jhalter** [comment]
Sure, I'll generalize this and add an option to the config file to exclude a list of patterns.

**Comment by jhalter** [comment]
@aptonline you'll want to manually add this into your config.yaml, as I don't have anything implemented to add new options to existing configs:

```
# List of Regular Expression filters for the Files list
IgnoreFiles:
  - '^\.*'     # Ignore all files starting with ".".  Leave this set if you are using the PreserveResourceForks option.
  - '^@'       # Ignore all files starting with "@"
 ```

**Comment by aptonline** [comment]
@jhalter Thats great, thanks for implementing this so quickly.

One thing I did have to change from the first option as including the `*` hid **all** files from the file directory but removing it solved the issue and still hid files files starting with `.`

`  - '^\.'     # Ignore all files starting with ".".  Leave this set if you are using the PreserveResourceForks option.`

**Comment by jhalter** [comment]
Thanks, I just ran into that too when I tried to update the Mobius Strip to the latest build.  Seems like a behavior difference between macOS and Linux.  

I've updated the default config so new users won't run into this.
