### ISSUE TITLE
Uploads getting stuck at finishing

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#48]
Seeing an issue where file uploads are getting stuck at finishing and when canceling the upload  it gives an error EOF in the logs and shows the file as completed but is corrupted when trying to use/expand. Using 1.8.5 client, 0.8.0 Server with PreserveResourceForks: false.

![Screenshot 2022-06-26 at 09 55 22](https://user-images.githubusercontent.com/190136/175809552-269dfe5b-d640-48eb-a1f4-373b97954d64.png)

**Comment by jhalter** [comment]
Thanks for pointing this out.  Should be fixed now in v0.8.1.

**Comment by aptonline** [comment]
Seems to be fixed for me now, thanks again for the turn around.
