### ISSUE TITLE
Building on MacOS

### ISSUE THREAD

**Issue by barracuda156** [jhalter/mobius#5]
Suggested method fails with: make: `*** No rule to make target `build-client'.  Stop.`

How to set up building from source correctly?

**Comment by jhalter** [comment]
Oops, I renamed the Makefile targets but didn't update the README.  

For now you can give this a shot: 

`make build-darwin-amd64-client`. 

 Or built directly with go:

`go build -o dist/mobius_client_darwin_amd64/mobius-hotline-client  cmd/mobius-hotline-client/main.go`

I'll make this more clear at some point.

**Comment by barracuda156** [comment]
> Oops, I renamed the Makefile targets but didn't update the README.
> 
> For now you can give this a shot:
> 
> `make build-darwin-amd64-client`.

Thank you for replying.
Would it work for powerpc (ppc and/or ppc64)? Should I just try `build-darwin-ppc64-client`?

**Comment by jhalter** [comment]
Hi, unfortunately I don't think this is a supported configuration in Go out of the box so you may be out of luck. 

You may have more success with the [shxd](http://synhxd.sourceforge.net) project, which is similar in that it provides a command line Hotline client and server but is implemented in C (I think?) .

**Comment by barracuda156** [comment]
> Hi, unfortunately I don't think this is a supported configuration in Go out of the box so you may be out of luck.
> 
> You may have more success with the [shxd](http://synhxd.sourceforge.net) project, which is similar in that it provides a command line Hotline client and server but is implemented in C (I think?) .

Thank you! Gonna try that one.
