### ISSUE TITLE
Option to log into file instead of to shell

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#66]
Hi!

When running the server all log output is forwarded to the shell per default (as usual in Linux etc).
It would be nice to have a configuration option to redirect all console log output into a file.

It seems like I stumbled upon a bug I'm trying to reproduce. Sometimes the server just stalls.
You don't get disconnected, but when this happens you can't load any files, written chat doesn't get posted in the chat window etc. Disconnecting and trying to connect again renders in the Hotline client (GLoarbLine 1.9.7) stalling at "Loggin in". The only fix is to restart Mobius. Happened twice today over the course of a few hours.

**Comment by jhalter** [comment]
Hi, I'm open to adding a command line option to log to file instead of stdout.  

Re: the freeze, does it seem to happen with the GLoarbLine client?  I've never tested with that client, so maybe I'm not handling some unexpected client behavior correctly.  I'll see if I can find a way to run it for testing.

**Comment by jhalter** [comment]
I've added optional logging to file v0.10.3 with the command line argument `-log-file=/path/to/file`

Also, just grabbed the GLoarbLine client.  Will give it a spin and see if I can reproduce a hang.

**Comment by Knezzen** [comment]
GLoarbLine is based on Openline which is based on the leaked original Hotline 1.9 sources, so they should be more or less on par.
The people that where active on the Hotline server when it happend all used GLoarbLine, so I'm not sure if it's a client or server issue so to say. I'll keep you posted if I find anything :)

**Comment by jhalter** [comment]
I played around with the GloarbeLine 1.9.7 client on Mac OS 9.1 for a bit, but couldn't reproduce any hangs.

If you could run the server with `-log-level=debug` and capture the logging around the time the hangs happen that may help narrow it down.

**Comment by Knezzen** [comment]
No hangs with the new version and logging works great. I'll open a new issue if the hanging persists.
