### ISSUE TITLE
Option to hide fork info files when listing folders

### ISSUE THREAD

**Issue by pfuentes69** [jhalter/mobius#70]
Hi,
I wonder if it's feasible to hide the extra files that are generated while activating the fork preservation feature.
Txs!

**Comment by jhalter** [comment]
Hi,
You can hide the files from the Hotline Files list by including this option in your config.yaml:

```
IgnoreFiles:
  - '^\.' 
```

I've added this to the default configuration a few releases ago, but your configuration may predate that.

**Comment by pfuentes69** [comment]
Ah!
I didn't notice these lines at the end of the sample config!
I applied it and works nicely now.

Do you deal with deletion of these files when deleting the main file? (I can manage if that's not the case, just to know :) 

Thanks!

**Comment by jhalter** [comment]
Yep, deletion happens automatically!

**Comment by pfuentes69** [comment]
Fantastic!

Thanks again!

(closing)
