### ISSUE TITLE
Some Windows and OSX clients fail to download small files

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#71]
So we stumbled upon a new issue. Sorry to hammer you with new tickets all the time, but I want to inform you with what we find.

We have a small file on our server in the uploads folder (Wikipedia.src.hqx) which is 6.7kb in size.
All Classic Mac OS clients I have been able to test with (Pitbull Pro 2.4.4, GLoarbLine 1.9.7, Hotline 1.2.3, Hotline 1.8.5) downloads it just fine. Obsession struggles but Nostalgia downloads it just fine on OSX (macOS). Pitbull Pro on Windows works as well as the original Hotline client. GLoarbLine and Underline on Windows doesn't. They seem to be able to download the file, but fail at the end with the error:
`Transfer failed! The connection closed before the transfer was complete.`

When this happens, I get this row in the log file:
`2022-11-07T13:59:54.808+0100	error	error serving request	{"RemoteAddr": "87.236.176.21:56745", "err": "invalid handshake"}`

And:
`2022-11-07T18:19:04.177+0100	error	file transfer error	{"reason": "invalid protocol"}`

Depending on clients trying to download.

**Comment by jhalter** [comment]
Thanks for all the details.  I’ll check it out.  

Any chance you can point me at the Windows versions of the Gloarbline and Underline clients?

**Comment by Knezzen** [comment]
You can find the clients here:
https://preterhuman.net/gethotlinekdx.php
http://www.lorbac.net/

**Comment by jhalter** [comment]
Thanks, I’m able to reproduce the problem on the official Windows clients as well.  Maybe I broke something for Windows when I added resource fork support.  😓

**Comment by jhalter** [comment]
I've released v0.10.6 with a change that seems to fix the problem in Underline and the official 1.2.3 client on Windows.

**Comment by Knezzen** [comment]
Seems to be working like it should! Thanks!
