### ISSUE TITLE
Writing in the public chat using Frogblast makes you disconnect from the server

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#72]
As the title mentions. I get the errors below in the log file.

> 2022-11-07T18:52:51.962+0100	debug	Received Transaction	{"remoteAddr": "MY_IP_ADDRESS:26247", "login": "guest", "RequestType": "tranChatSend"}
> 2022-11-07T18:52:51.962+0100	error	PANIC	{"err": "runtime error: invalid memory address or nil pointer dereference", "trace": "goroutine 15733 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/jhalter/mobius/hotline.dontPanic(0xc000002460?)\n\t/home/circleci/project/hotline/panic.go:13 +0xb2\npanic({0x7bfb00, 0xb0f9d0})\n\t/usr/local/go/src/runtime/panic.go:890 +0x262\ngithub.com/jhalter/mobius/hotline.HandleChatSend(0xc000002460, 0xc00036c6c0)\n\t/home/circleci/project/hotline/transaction_handlers.go:262 +0x692\ngithub.com/jhalter/mobius/hotline.(*ClientConn).handleTransaction(0xc000002460, {0x0, 0x0, 0x0, {0xc000337142, 0x2, 0x26}, {0xc000337144, 0x4, 0x24}, ...})\n\t/home/circleci/project/hotline/client_conn.go:83 +0xae3\ngithub.com/jhalter/mobius/hotline.(*Server).handleNewConnection(0xc000348ff0, {0x2?, 0x2?}, {0x7f2754d73218, 0xc0004a8068}, {0xc0003446c0, 0x12})\n\t/home/circleci/project/hotline/server.go:705 +0x2b65\ngithub.com/jhalter/mobius/hotline.(*Server).Serve.func1()\n\t/home/circleci/project/hotline/server.go:200 +0x1ba\ncreated by github.com/jhalter/mobius/hotline.(*Server).Serve\n\t/home/circleci/project/hotline/server.go:196 +0x98\n"}

**Comment by jhalter** [comment]
This is fixed now in the 0.10.5 release
