### ISSUE TITLE
Nick gets changed to part of the chat message

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#75]
And another one! Sorry to pester you about these, I just want to help out. Thanks again for a wonderful addition to the Hotline software base! :)

We have a quite active chat on our server and have observed a few times now that nicks can change to a part of that persons chat message when the chat gets very active. Seems to happen spontaneously regardless of client.

Had one user change his nick to "Btw, " just now, hence me opening this ticket. "Btw, " was the start of the chat he posted at that instance. It happens a few times per day and you just log out and in again and you have your nickname and icon back. Still, it's a bit frustrating.

**Comment by Knezzen** [comment]
It happens when you write a lot of text and only with HL 1.2.3 clients. Just tried pasting in a lot of text in the chat and it's reproducable.

I want to invite you to join us at **hotline.system7today.com** for some nice a friendly System 7 centric chat, btw :)

**Comment by jhalter** [comment]
Hi, I ran into this once, but I couldn't figure out how to reproduce it because I'm usually testing on the 1.9.2 client.  I'm able to reproduce it on the 1.2.3 client now, so that should help me work it out.  Thanks!
