### ISSUE TITLE
Docker Builds

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#77]
Hi, long time no see, I keep trying to catch you on Möbius strip but time zones aren't ideal lol.

I've just got round to updating my instance of Mobius server and noted that the docker hub version is out of date, 0.9.1 seems to be the most recent version if I use the latest tag.  Are these builds still being maintained?

**Comment by jhalter** [comment]
Oops, I haven't released in a few months and forgot to update the Docker image and brew formula.  Done.  Thanks for the reminder.  I need to automate this at some point. 

Sorry I keep missing you when you stop by the Hotline server.  Look forward to catching up soon!
