### ISSUE TITLE
Server hangs when user logs out abruptly

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#81]
Another one!

I have had some strange behavior on and off and finally managed to trace it down to abrupt user logout in some way (Hotline client crashing, network connection dying abruptly etc).

When this happens I get the following line in the logfile:
`2022-11-21T14:41:08.170+0100	error	error sending transaction	{"err": "invalid client id [0 15]"}`

When this happens the server doesn't crash, but more or less stops responding for the rest of the connected users (can't load any files, news, posting in the chat returns nothing etc). Tying to disconnect and then reconnect stops at the login stage to the server (see attached screenshot). This is the stage you stop at regardless of the client, I just happened to be logged in using Nostagia when it happened this time, hence the screenshot of Nostalgia.

![nostalgia](https://user-images.githubusercontent.com/27211475/203102955-50621e2f-c440-42de-8324-a6f8885eeba4.png)

**Comment by jhalter** [comment]
Thanks for narrowing this down with the logs.  This looks like a dumb bug with a simple fix.

New version incoming...

**Comment by jhalter** [comment]
Pretty sure this is fixed in v0.10.10, but let me know if you still run into it.

Thanks again!
