### ISSUE TITLE
I'm probably doing something wrong, but I can't download files with the OSX terminal client

### ISSUE THREAD

**Issue by StariusPrime** [jhalter/mobius#85]
Hello!

I don't know if I'm doing something wrong, but when I navigate to a file on a server in the Mobius client, I can't figure out how to download it.  I hit enter, or most any key I can think of, and nothing happens.  

Am I missing something?

**Comment by jhalter** [comment]
Hi, apologies for the confusion.  The client doesn't support file transfers yet, but it's on my roadmap.

**Comment by StariusPrime** [comment]
> Hi, apologies for the confusion. The client doesn't support file transfers yet, but it's on my roadmap.

Ah, thank you for the clarification! 👍

**Comment by jhalter** [comment]
Yeah, I guess there are not many Apple Silicon native Hotline clients out there.  I'm on an M1 MacBook Pro, but I spend most of my Hotline time running the official 1.2.3 or 1.9.2 clients inside Basilisk II or Sheepshaver.

The Nostalgia client seems to run fine with Rosetta 2, but it doesn't really bring the vintage experience that I'm personally looking for.

**Comment by StariusPrime** [comment]
Yeah, I've gotten Nostalgia to run, but I can't get any trackers to work or display on it, so its kind of dead in the water for me there... though I must confess, I've not tried connecting to a server manually.

**Comment by StariusPrime** [comment]
I may just have to bring out the old G4 Desktop to come back to the Hotline world. 😅

**Comment by jhalter** [comment]
>  I can't get any trackers to work or display on in

I guess I've only ever used it to test my own server, but yeah the tracker list is dead for me too.  It doesn't seem to even send any outbound request, based on tcpdump observations.  Not sure what the deal is.

**Comment by Knezzen** [comment]
@StariusPrime Obsession is under active development and can list trackers just fine.
It's my go to client on my M1 MacBook Air, despite the current release being Intel only at the moment.

Find it here: https://github.com/tjohnman/Obsession

**Comment by StariusPrime** [comment]
> 

Thanks, yeah, I've tried Obsession. I find it's very hit or miss being able to download something from a server.  Sometimes it locks up for me just trying to open a file directory.  Sometimes it tries to download a file and just hangs there.  Sometimes it looks like it will download a file but hangs at 0 kbps.   So far I've actually been able to download 1 file with it.  

Even testing it on the Mobius Strip server, I get this:  
![Screenshot 2023-01-13 at 5 52 26 AM](https://user-images.githubusercontent.com/65854873/212314414-5aa87bd8-1548-4877-9fb4-8a6f0c92d1b4.png)

Also, even if I did get  downloads to work, it wants to put them all on the desktop with no apparent way I can find to change the location.  

😔 So my experience with Obsession has been less than ideal here also unfortunately.

**Comment by jhalter** [comment]
@StariusPrime Check out this new project if you're still looking for an Apple Silicon Hotline client: https://github.com/mierau/hotline

I'm going to close this issue, as it seems unlikely that'll be adding file transfers to the CLI client anytime soon.

**Comment by StariusPrime** [comment]
Thank you very much for sending me a link to this project!
It looks very interesting, I will check it out!
