### ISSUE TITLE
Threaded news broken on some third party clients

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#87]
Hi!

Recently stumbled upon an issue or bug or whatever to call it when trying to make some categories in the threaded news section. It works like it should on the official Hotline clients as well as clients based on the original Hotline Connect sources (GLoarbLine, Openline, Underline etc) but is broken in third party clients like Heidrun, Frogblast and Pitbull Pro. There's garbage 0 byte posts in the threaded section and I can't add new news. Frogblasts shows the posts without the "garbage" but doesn't list the actual text included in the post.

Frogblast:
![frogblast_error](https://user-images.githubusercontent.com/27211475/212370278-f9d9a2ed-3905-4f39-a36b-d3edcb5b365a.png)

Heidrun:
![heidrun_error](https://user-images.githubusercontent.com/27211475/212370284-768449a5-7214-4669-b109-85ad67ddb8c0.png)

Pitbull Pro:
![pitbullpro_error](https://user-images.githubusercontent.com/27211475/212370286-3d0c42ca-cc86-46d6-a282-0a5f7a1bdb2c.png)

Screenshot of GLoarbLine working like it should:
![gloarbline_working](https://user-images.githubusercontent.com/27211475/212370281-87e772e4-9a6c-4977-981c-60464736d2d6.png)

**Comment by jhalter** [comment]
Thanks for the detailed report!  I'll take a look.

**Comment by jhalter** [comment]
I've made some progress on Frogblast:

<img width="912" alt="Screenshot 2023-01-15 at 5 33 03 PM" src="https://user-images.githubusercontent.com/868228/212580443-78ba50ad-f5e4-48ef-956b-d7de01dad7b1.png">

I'll check out the others in a few days.

**Comment by jhalter** [comment]
I found the bug affecting Heldrun.  Probably the same issue that is hurting Pitbull clients, but I haven't tested that out yet.

<img width="912" alt="Screenshot 2023-01-16 at 2 18 28 PM" src="https://user-images.githubusercontent.com/868228/212773570-f1469c02-8398-45e4-9d1a-4b024151ab4b.png">

Progress!

I would like to do some cleanup and add test coverage before I ship this though, so it'll be a bit longer...

**Comment by jhalter** [comment]
This should be fixed in v0.10.13.

**Comment by jhalter** [comment]
Also can you point me at a source for the Pitbull Pro version that you have a screenshot of?  I couldn't find it on Preterhuman's site.

**Comment by Knezzen** [comment]
Great! Will update my server this weekend. Thanks for looking into this! :)

You can find Pitbull Pro 2.4.4 here: http://macintoshgarden.org/apps/pitbull-pro-244

**Comment by Knezzen** [comment]
All is well. Just updated my "production server" and the issue is gone :)

**Comment by jhalter** [comment]
Hi @Knezzen looks like I broke the article threading, but I've fixed it in v0.10.16.  Apologies for all the version churn.

**Comment by Knezzen** [comment]
Everything seems to be working now! Thanks for all your efforts @jhalter :)
