### ISSUE TITLE
Happy MARCHintosh!

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#94]
Hi Jeff, hope you are doing well.  Not spoken in a while but wanted to drop by to say hi and to let you know that I'm still using Mobius daily (well the server is running daily) and I get the occasional notification when someone joins :)

Decided to celebrate MARCHintosh by promoting the RetroMac server and also giving Mobius a shout out in the process.

https://mas.to/@apt/109965616923585834

Lets catch-up again soon...

Ade

**Comment by jhalter** [comment]
Hey there, thanks for the promo.  Awesome to hear that you're keeping the Hotline flame burning.

Look forward to catching up soon!
