### ISSUE TITLE
Server crash after extensive logging on and off

### ISSUE THREAD

**Issue by Knezzen** [jhalter/mobius#95]
Had a trolling user that kept logging on and off with different IP's and me trying to ban every IP he used.

The server started behaving strangely after a while.
Usernames kept changing sporadically or disappeared all together, leaving only the icons in the userlist.

When this happend, the following lines appeared in the log file, shortly before I got disconnected and I couldn't make a new connection without restarting Mobius:

> 2023-03-15T12:31:02.082+0100    error   error sending transaction       {"err": "write tcp my.internal.ip:5500->84.26.66.193:65082: use of closed network connection"}
> 2023-03-15T12:31:02.082+0100    error   PANIC   {"err": "runtime error: invalid memory address or nil pointer dereference", "trace": "goroutine 88535 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/jhalter/mobius/hotline.dontPanic(0xc0000be2a0?)\n\t/home/circleci/project/hotline/panic.go:13 +0xb2\npanic({0x7bfb00, 0xb0f9d0})\n\t/usr/local/go/src/runtime/panic.go:890 +0x262\ngithub.com/jhalter/mobius/hotline.(*ClientConn).String(0xc00011c0e0)\n\t/home/circleci/project/hotline/client_conn.go:247 +0x495\ngithub.com/jhalter/mobius/hotline.HandleGetClientInfoText(0xc0000be2a0, 0xc0003300c0)\n\t/home/circleci/project/hotline/transaction_handlers.go:923 +0x456\ngithub.com/jhalter/mobius/hotline.(*ClientConn).handleTransaction(0xc0000be2a0, {0x0, 0x0, 0x0, {0xc0002fa322, 0x2, 0x1a}, {0xc0002fa324, 0x4, 0x18}, ...})\n\t/home/circleci/project/hotline/client_conn.go:82 +0xae3\ngithub.com/jhalter/mobius/hotline.(*Server).handleNewConnection(0xc000388ff0, {0x2?, 0x2?}, {0x7f3ebc7717d8, 0xc000090000}, {0xc00001c078, 0x15})\n\t/home/circleci/project/hotline/server.go:708 +0x2ae5\ngithub.com/jhalter/mobius/hotline.(*Server).Serve.func1()\n\t/home/circleci/project/hotline/server.go:197 +0x1ba\ncreated by github.com/jhalter/mobius/hotline.(*Server).Serve\n\t/home/circleci/project/hotline/server.go:193 +0x98\n"}

**Comment by Knezzen** [comment]
The issue seem to happen when you try to interact with a user that logged on without a nickname (just an icon in the userlist, no nickname specified). Try to get the users info or try to write a chat to the user.

**Comment by jhalter** [comment]
Hi, sorry you went through that.  Also wow, I'm surprised that there are still bad actors among the small Hotline community!

Thanks for the logs.  I'll take a look when I can.

**Comment by Knezzen** [comment]
This was someone who was banned on our Discord server and noticed he could "get through" to Discord using Hotline. When I shut down the Discord integration temporarily he started abusing the Hotline server instead. Some people are just... people.

Well, he or she triggered the bug in Mobius (or whatever it is), so I guess theres some kind of silver lining at least ;)

**Comment by jhalter** [comment]
I've made a change in v0.10.18 to disconnect banned users earlier in the connection flow.  I think this should fix this issue.

**Comment by Knezzen** [comment]
Thanks for the quick fix, Jeff! :-)
