### ISSUE TITLE
Provide DDNS hostname to tracker?

### ISSUE THREAD

**Issue by aptonline** [jhalter/mobius#99]
Not sure if this is possible but is there anyway to provide a DDNS hostname to a tracker as opposed to an IP or are all tracker entries IP based?

**Comment by jhalter** [comment]
Hey Apt.  In the Hotline protocol the server doesn't sent either the IP or a hostname to the tracker, just a port number.  The tracker uses the source IP of the registration request as the server address.  So in that sense it's already dynamic, although in Mobius there's a 5 minute interval between tracker updates so there is a window where it is out of date.  Same is true for DNS though.

<img width="671" alt="Screenshot 2023-03-29 at 8 40 14 AM" src="https://user-images.githubusercontent.com/868228/228592757-c09a3931-847c-4f66-9bf8-aaae940dcf1f.png">

**Comment by aptonline** [comment]
Interesting, thanks for providing that information, I assumed it did provide an address as when you manually choose to connect to a server you provide an IP.

The use case I was thinking of is if you wanted to hide the ip from casual view (you can always find the information from a host and obvs) if you say provided server details as a link in a message or if it was indeed provided to the tracker.
